version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "GHA"

  # uv is currently not supported
  # https://github.com/dependabot/dependabot-core/issues/10478
