# Generated by Django 4.2.5 on 2023-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Electricity",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("units_kwh", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated", models.BooleanField()),
                ("reading", models.IntegerField()),
                ("comments", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Gas",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("units_kwh", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated", models.BooleanField()),
                ("reading", models.IntegerField()),
                ("comments", models.CharField(max_length=200)),
            ],
        ),
    ]
